### ISSUE TITLE
New libraries 

### ISSUE THREAD

**Issue by TomasRoj** [arduino/season-of-docs#1]
Hey,

Is somewhere avilibe list of new libraries so I can help their makers with documentation?

**Comment by per1234** [comment]
This repository is for the [Google Season of Docs](https://developers.google.com/season-of-docs/) program. Please only create issues here specifically related to participation in that program.

---
As to your question: here is a GitHub search for repositories with the `arduino-library` topic that were created in 2019.
https://github.com/search?q=created%3A%3E2019-01-01+topic%3Aarduino-library

You can adapt that search as you like, following this guide:
https://help.github.com/en/articles/searching-for-repositories

If you would like to discuss opportunities to contribute to the Arduino project, we can do that on the Arduino Forum in the thread you created for that purpose:
http://forum.arduino.cc/index.php?topic=607386
